// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;
import java.util.*;

public class LoginTest {
  private WebDriver driver;
  private WebDriverWait wait;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    WebDriverManager.firefoxdriver().setup(); // Optional: manages driver binaries
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    wait = new WebDriverWait(driver, Duration.ofSeconds(15));
    vars = new HashMap<>();
    driver.manage().window().setSize(new Dimension(862, 993));
  }

  @After
  public void tearDown() {
    driver.quit();
  }

//  @Test
//  public void login() {
//    // Step 1: Open sign-in page
//    driver.get("http://localhost:4000/sign_in");
//
//    // Step 2: Click the first button (assumed to be a sign-in trigger)
//    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button"))).click();
//
//    // Step 3: Click link with text "John Doe"
//    wait.until(ExpectedConditions.elementToBeClickable(By.linkText("John Doe"))).click();
//
//    // Step 4: Click view-container
//    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".view-container"))).click();
//
//    // Step 5: Click "John Doe" again
//    wait.until(ExpectedConditions.elementToBeClickable(By.linkText("John Doe"))).click();
//
//    // Step 6: Assert the name "John Doe" appears in the expected span
//    WebElement nameSpan = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("span:nth-child(3)")));
//    assertThat(nameSpan.getText(), is("John Doe"));
//  }
@Test
public void login() {
  LoginPage loginPage = new LoginPage(driver);
  loginPage.open();
  loginPage.clickSignInButton();
  loginPage.clickUserLink("John Doe");
  loginPage.clickViewContainer();
  loginPage.clickUserLink("John Doe");
  assertThat(loginPage.getDisplayedName(), is("John Doe"));
}

}
