// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;

public class SignUpTest {
  private WebDriver driver;
  private WebDriverWait wait;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    WebDriverManager.firefoxdriver().setup();
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    wait = new WebDriverWait(driver, Duration.ofSeconds(15));
    vars = new HashMap<>();
    driver.manage().window().setSize(new Dimension(771, 993));
  }

  @After
  public void tearDown() {
    driver.quit();
  }

//  @Test
//  public void signUp() {
//    driver.get("http://localhost:4000/sign_in");
//
//    wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Create new account"))).click();
//
//    WebElement firstName = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("user_first_name")));
//    firstName.sendKeys("toha");
//    firstName.sendKeys(Keys.ENTER);
//
//    WebElement lastName = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("user_last_name")));
//    lastName.sendKeys("kitty");
//    lastName.sendKeys(Keys.ENTER);
//
//    WebElement email = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("user_email")));
//    email.sendKeys("toha@kutty.com");
//    email.sendKeys(Keys.ENTER);
//
//    // Correct the email if needed
//    email = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("user_email")));
//    email.clear();
//    email.sendKeys("tohaa@kitty.com");
//    email.sendKeys(Keys.ENTER);
//
//    WebElement password = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("user_password")));
//    password.sendKeys("hellokitty");
//    password.sendKeys(Keys.ENTER);
//
//    WebElement confirmPassword = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("user_password_confirmation")));
//    confirmPassword.sendKeys("hellokitty");
//    confirmPassword.sendKeys(Keys.ENTER);
//
//    WebElement nameSpan = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("span:nth-child(3)")));
//    assertThat(nameSpan.getText(), is("toha kitty"));
//  }
@Test
public void signUp() {
  SignUpPage signUpPage = new SignUpPage(driver);
  signUpPage.open();
  signUpPage.clickCreateAccount();
  signUpPage.enterFirstName("toha");
  signUpPage.enterLastName("kitty");
  signUpPage.enterEmail("toha@kutty.com");
  signUpPage.correctEmail("tohaa@kitty.com");
  signUpPage.enterPassword("hellokitty");
  signUpPage.enterConfirmPassword("hellokitty");
  assertThat(signUpPage.getDisplayedName(), is("toha kitty"));
}

}
